version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - sms-api
    restart: unless-stopped
    networks:
      - project_network

networks:
  project_network:
    external: true
    name: project_network